apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name}}-{{ .Values.app.name }}
  labels:
    app: {{ .Values.postgres.name}}-{{ .Values.app.name }}
    namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  serviceName: {{ .Values.postgres.name}}-{{ .Values.app.name }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name}}-{{ .Values.app.name }}
      namespace: {{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name}}-{{ .Values.app.name }}
        namespace: {{ .Release.Namespace }}
    spec:
      containers:
        - name: {{ .Values.postgres.name}}-{{ .Values.app.name }}
          image: {{ .Values.postgres.image }}
          volumeMounts:
            - mountPath: {{ .Values.postgres.pvc.containerPath }}
              name: {{ .Values.postgres.name}}-{{ .Values.app.name }}
          env:
            {{- toYaml .Values.postgres.env | nindent 12 }}
          ports:
            {{- toYaml .Values.postgres.ports | nindent 12 }}
      volumes:
      - name: {{ .Values.postgres.name}}-{{ .Values.app.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.name}}-{{ .Values.app.name }}
