"""init

Revision ID: b7e4b44fa701
Revises:
Create Date: 2024-04-26 20:52:15.123942

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7e4b44fa701"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_table(
        "book",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("ext", sa.Text(), nullable=False),
        sa.Column("cover", sa.Text(), nullable=False),
        sa.Column("file", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_table(
        "category",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["public.category.id"], name="category_parent_fk", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_table(
        "m2m_author_book",
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["public.author.id"], name="fk_m2m_author_book_on_author", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["book_id"], ["public.book.id"], name="fk_m2m_author_book_on_book", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("book_id", "author_id", name="pk_m2m_author_book"),
        schema="public",
    )
    op.create_table(
        "m2m_category_book",
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["public.book.id"], name="fk_m2m_category_book_on_book", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["public.category.id"], name="fk_m2m_category_book_on_category", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("book_id", "category_id", name="pk_m2m_category_book"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("m2m_category_book", schema="public")
    op.drop_table("m2m_author_book", schema="public")
    op.drop_table("category", schema="public")
    op.drop_table("book", schema="public")
    op.drop_table("author", schema="public")
    # ### end Alembic commands ###
